#!/bin/bash 
# Basic parameters: job name, parallel environment and cores, queue, used shell, 
# current working directory,output files (.err, .out), email.
#$ -N name
#$ -pe smp 1
#$ -q iqtc04.q
#$ -S /bin/bash
#$ -cwd 
#$ -o vasp.out 
#$ -e vasp.err 
# Remove the first '#' of the following 2 lines if you want to receive an email when the job ends.
##$ -m e 

# Load the modules needed 
. /etc/profile
module load vasp/5.4.1_ompi

# Copy inputs and files needed to the directory where the jobs will run 
export DIR=$PWD
cd $TMPDIR 
cp $DIR/* .

# Run the job 

# -------------> WARNING <-------------------
# Check what binary fits your needs
# vasp             MPI parallel, charge density and wavefunction complex
# vasp_cd          MPI parallel, charge density: half grid mode (-DNGZhalf)
# vasp_gamma       MPI parallel, gamma-point only (-DwNGZhalf)
# vasp_vtst        MPI parallel, charge density + wavefunction complex + VASP TST Tools
# vasp_vtst_cd     MPI parallel, charge density: half grid mode (-DNGZhalf) + VASP TST Tools
# vasp_vtst_gamma  MPI parallel, gamma-point only (-DwNGZhalf) + VASP TST Tools
# -------------------------------------------

export OMP_NUM_THREADS=1
mpirun -np $NSLOTS vasp

# Copy the results to our home directory
cp * $DIR
